Repository spirit-of-christmas/spectrum, pull requests merged in 2024-03, with the labels that each got.

#81 #80 Added tags to scheduled events
  info/management/commands/reschedule.py
Labels: bug

#86 #77 Implemented feature to hide event
  info/forms.py
  info/migrations/0036_event_hide.py
  info/models.py
  info/views/events.py
  info/views/index.py
Labels: enhancement

#87 Merge main into production
  info/forms.py
  info/migrations/0036_event_hide.py
  info/models.py
  info/views/events.py
  info/views/index.py
Labels: enhancement

#91 Footer/#67
  help/templates/help/contacts.html
  help/templates/help/contacts_add.html
  help/templates/help/contacts_delete.html
  help/templates/help/contacts_edit.html
  help/templates/help/events.html
  help/templates/help/events_add.html
  help/templates/help/events_delete.html
  help/templates/help/events_edit.html
  help/templates/help/index.html
  help/templates/help/locations.html
  help/templates/help/locations_add.html
  help/templates/help/locations_delete.html
  help/templates/help/locations_edit.html
  help/templates/help/organisations.html
  help/templates/help/organisations_edit.html
  help/templates/help/resources.html
  help/templates/help/resources_add.html
  help/templates/help/resources_delete.html
  help/templates/help/resources_edit.html
  spectrum/templates/base.html
Labels: enhancement

#93 Bug/92
  Dockerfile
  info/urls.py
  info/views/__init__.py
  info/views/resources.py
  poetry.lock
  pyproject.toml
Labels: bug

#98 #97 Switched to gunicorn
  docker-compose.yml
  pyproject.toml
Labels: enhancement

#100 #99 Fixed regression in Dockerfile
  docker-compose.yml
  help/templates/help/contacts.html
  help/templates/help/contacts_add.html
  help/templates/help/contacts_delete.html
  help/templates/help/contacts_edit.html
  help/templates/help/events.html
  help/templates/help/events_add.html
  help/templates/help/events_delete.html
  help/templates/help/events_edit.html
  help/templates/help/index.html
  help/templates/help/locations.html
  help/templates/help/locations_add.html
  help/templates/help/locations_delete.html
  help/templates/help/locations_edit.html
  help/templates/help/organisations.html
  help/templates/help/organisations_edit.html
  help/templates/help/resources.html
  help/templates/help/resources_add.html
  help/templates/help/resources_delete.html
  help/templates/help/resources_edit.html
  info/static/info/css/global.css
  info/templates/info/event_detail.html
  info/templates/info/events.html
  info/templates/info/organisation_detail.html
  info/templates/info/organisation_list.html
  info/templates/info/resource_detail.html
  info/templates/info/resources.html
  poetry.lock
  spectrum/templates/base.html
Labels: bug

#102 #101 Added footer text
  spectrum/templates/base.html
Labels: enhancement

#103 #96 Added license
  LICENSE.md
Labels: enhancement

#107 Release 23.04v1
  Dockerfile
  LICENSE.md
  docker-compose.yml
  help/templates/help/contacts.html
  help/templates/help/contacts_add.html
  help/templates/help/contacts_delete.html
  help/templates/help/contacts_edit.html
  help/templates/help/events.html
  help/templates/help/events_add.html
  help/templates/help/events_delete.html
  help/templates/help/events_edit.html
  help/templates/help/index.html
  help/templates/help/locations.html
  help/templates/help/locations_add.html
  help/templates/help/locations_delete.html
  help/templates/help/locations_edit.html
  help/templates/help/organisations.html
  help/templates/help/organisations_edit.html
  help/templates/help/resources.html
  help/templates/help/resources_add.html
  help/templates/help/resources_delete.html
  help/templates/help/resources_edit.html
  info/static/info/css/global.css
  info/templates/info/contact_form.html
  info/templates/info/contact_list.html
  info/templates/info/dashboard.html
  info/templates/info/dashboard_org.html
  info/templates/info/event_detail.html
  info/templates/info/event_form.html
  info/templates/info/event_list.html
  info/templates/info/events.html
  info/templates/info/location_form.html
  info/templates/info/location_list.html
  info/templates/info/organisation_detail.html
  info/templates/info/organisation_list.html
  info/templates/info/resource_detail.html
  info/templates/info/resource_form.html
  info/templates/info/resource_list.html
  info/templates/info/resources.html
  info/urls.py
  info/views/__init__.py
  info/views/resources.py
  poetry.lock
  pyproject.toml
  spectrum/templates/base.html
  spectrum/templates/dashboard_base.html
Labels: release
